// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CreateItemRequestStatus.
const (
	CreateItemRequestStatusActive   CreateItemRequestStatus = "active"
	CreateItemRequestStatusInactive CreateItemRequestStatus = "inactive"
)

// Valid indicates whether the value is a known member of the CreateItemRequestStatus enum.
func (e CreateItemRequestStatus) Valid() bool {
	switch e {
	case CreateItemRequestStatusActive:
		return true
	case CreateItemRequestStatusInactive:
		return true
	default:
		return false
	}
}

// Defines values for UpdateItemRequestStatus.
const (
	UpdateItemRequestStatusActive   UpdateItemRequestStatus = "active"
	UpdateItemRequestStatusInactive UpdateItemRequestStatus = "inactive"
)

// Valid indicates whether the value is a known member of the UpdateItemRequestStatus enum.
func (e UpdateItemRequestStatus) Valid() bool {
	switch e {
	case UpdateItemRequestStatusActive:
		return true
	case UpdateItemRequestStatusInactive:
		return true
	default:
		return false
	}
}

// Defines values for ListItemsParamsStatus.
const (
	Active   ListItemsParamsStatus = "active"
	Inactive ListItemsParamsStatus = "inactive"
)

// Valid indicates whether the value is a known member of the ListItemsParamsStatus enum.
func (e ListItemsParamsStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  *string       `json:"access_token,omitempty"`
	RefreshToken *string       `json:"refresh_token,omitempty"`
	User         *UserResponse `json:"user,omitempty"`
}

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	Description *string                  `json:"description,omitempty"`
	Status      *CreateItemRequestStatus `json:"status,omitempty"`
	Title       string                   `json:"title"`
}

// CreateItemRequestStatus defines model for CreateItemRequest.Status.
type CreateItemRequestStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Non-zero application error code
	Code int `json:"code"`

	// Data Always null for error responses
	Data interface{} `json:"data"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// ItemResponse defines model for ItemResponse.
type ItemResponse struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *int       `json:"id,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Title       *string    `json:"title,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	UserId      *int       `json:"user_id,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PagedItemsResponse defines model for PagedItemsResponse.
type PagedItemsResponse struct {
	Items      *[]ItemResponse `json:"items,omitempty"`
	Page       *int            `json:"page,omitempty"`
	PageSize   *int            `json:"page_size,omitempty"`
	Total      *int            `json:"total,omitempty"`
	TotalPages *int            `json:"total_pages,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// Response defines model for Response.
type Response struct {
	Code    *int                    `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

// UpdateItemRequest defines model for UpdateItemRequest.
type UpdateItemRequest struct {
	Description *string                  `json:"description,omitempty"`
	Status      *UpdateItemRequestStatus `json:"status,omitempty"`
	Title       *string                  `json:"title,omitempty"`
}

// UpdateItemRequestStatus defines model for UpdateItemRequest.Status.
type UpdateItemRequestStatus string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email    *string `json:"email,omitempty"`
	Id       *int    `json:"id,omitempty"`
	Role     *string `json:"role,omitempty"`
	Username *string `json:"username,omitempty"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	Page     *int                   `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int                   `form:"page_size,omitempty" json:"page_size,omitempty"`
	Keyword  *string                `form:"keyword,omitempty" json:"keyword,omitempty"`
	Status   *ListItemsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListItemsParamsStatus defines parameters for ListItems.
type ListItemsParamsStatus string

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = UpdateItemRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with credentials
	// (POST /api/v1/auth/login)
	LoginUser(c *gin.Context)
	// Get current user profile
	// (GET /api/v1/auth/profile)
	GetProfile(c *gin.Context)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(c *gin.Context)
	// Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(c *gin.Context)
	// List items with pagination
	// (GET /api/v1/items)
	ListItems(c *gin.Context, params ListItemsParams)
	// Create a new item
	// (POST /api/v1/items)
	CreateItem(c *gin.Context)
	// Soft delete an item
	// (DELETE /api/v1/items/{id})
	DeleteItem(c *gin.Context, id int)
	// Get item by ID
	// (GET /api/v1/items/{id})
	GetItem(c *gin.Context, id int)
	// Update an item
	// (PUT /api/v1/items/{id})
	UpdateItem(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginUser(c)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfile(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterUser(c)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "keyword" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "keyword", c.Request.URL.Query(), &params.Keyword, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter keyword: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListItems(c, params)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateItem(c)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteItem(c, id)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItem(c, id)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateItem(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.LoginUser)
	router.GET(options.BaseURL+"/api/v1/auth/profile", wrapper.GetProfile)
	router.POST(options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshToken)
	router.POST(options.BaseURL+"/api/v1/auth/register", wrapper.RegisterUser)
	router.GET(options.BaseURL+"/api/v1/items", wrapper.ListItems)
	router.POST(options.BaseURL+"/api/v1/items", wrapper.CreateItem)
	router.DELETE(options.BaseURL+"/api/v1/items/:id", wrapper.DeleteItem)
	router.GET(options.BaseURL+"/api/v1/items/:id", wrapper.GetItem)
	router.PUT(options.BaseURL+"/api/v1/items/:id", wrapper.UpdateItem)
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse struct {
	Code    *int          `json:"code,omitempty"`
	Data    *AuthResponse `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser400JSONResponse ErrorResponse

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401JSONResponse ErrorResponse

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser500JSONResponse ErrorResponse

func (response LoginUser500JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProfileRequestObject struct {
}

type GetProfileResponseObject interface {
	VisitGetProfileResponse(w http.ResponseWriter) error
}

type GetProfile200JSONResponse struct {
	Code    *int          `json:"code,omitempty"`
	Data    *UserResponse `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetProfile200JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProfile401JSONResponse ErrorResponse

func (response GetProfile401JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProfile404JSONResponse ErrorResponse

func (response GetProfile404JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProfile500JSONResponse ErrorResponse

func (response GetProfile500JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse struct {
	Code    *int          `json:"code,omitempty"`
	Data    *AuthResponse `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken400JSONResponse ErrorResponse

func (response RefreshToken400JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken401JSONResponse ErrorResponse

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken500JSONResponse ErrorResponse

func (response RefreshToken500JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse struct {
	Code    *int          `json:"code,omitempty"`
	Data    *AuthResponse `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser400JSONResponse ErrorResponse

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse ErrorResponse

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser500JSONResponse ErrorResponse

func (response RegisterUser500JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListItemsRequestObject struct {
	Params ListItemsParams
}

type ListItemsResponseObject interface {
	VisitListItemsResponse(w http.ResponseWriter) error
}

type ListItems200JSONResponse struct {
	Code    *int                `json:"code,omitempty"`
	Data    *PagedItemsResponse `json:"data,omitempty"`
	Message *string             `json:"message,omitempty"`
}

func (response ListItems200JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListItems500JSONResponse ErrorResponse

func (response ListItems500JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateItemRequestObject struct {
	Body *CreateItemJSONRequestBody
}

type CreateItemResponseObject interface {
	VisitCreateItemResponse(w http.ResponseWriter) error
}

type CreateItem201JSONResponse struct {
	Code    *int          `json:"code,omitempty"`
	Data    *ItemResponse `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response CreateItem201JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateItem400JSONResponse ErrorResponse

func (response CreateItem400JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateItem500JSONResponse ErrorResponse

func (response CreateItem500JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteItemRequestObject struct {
	Id int `json:"id"`
}

type DeleteItemResponseObject interface {
	VisitDeleteItemResponse(w http.ResponseWriter) error
}

type DeleteItem200JSONResponse Response

func (response DeleteItem200JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteItem404JSONResponse ErrorResponse

func (response DeleteItem404JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteItem500JSONResponse ErrorResponse

func (response DeleteItem500JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetItemRequestObject struct {
	Id int `json:"id"`
}

type GetItemResponseObject interface {
	VisitGetItemResponse(w http.ResponseWriter) error
}

type GetItem200JSONResponse struct {
	Code    *int          `json:"code,omitempty"`
	Data    *ItemResponse `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetItem200JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetItem404JSONResponse ErrorResponse

func (response GetItem404JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetItem500JSONResponse ErrorResponse

func (response GetItem500JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateItemRequestObject struct {
	Id   int `json:"id"`
	Body *UpdateItemJSONRequestBody
}

type UpdateItemResponseObject interface {
	VisitUpdateItemResponse(w http.ResponseWriter) error
}

type UpdateItem200JSONResponse struct {
	Code    *int          `json:"code,omitempty"`
	Data    *ItemResponse `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UpdateItem200JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateItem400JSONResponse ErrorResponse

func (response UpdateItem400JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateItem404JSONResponse ErrorResponse

func (response UpdateItem404JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateItem500JSONResponse ErrorResponse

func (response UpdateItem500JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login with credentials
	// (POST /api/v1/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Get current user profile
	// (GET /api/v1/auth/profile)
	GetProfile(ctx context.Context, request GetProfileRequestObject) (GetProfileResponseObject, error)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// List items with pagination
	// (GET /api/v1/items)
	ListItems(ctx context.Context, request ListItemsRequestObject) (ListItemsResponseObject, error)
	// Create a new item
	// (POST /api/v1/items)
	CreateItem(ctx context.Context, request CreateItemRequestObject) (CreateItemResponseObject, error)
	// Soft delete an item
	// (DELETE /api/v1/items/{id})
	DeleteItem(ctx context.Context, request DeleteItemRequestObject) (DeleteItemResponseObject, error)
	// Get item by ID
	// (GET /api/v1/items/{id})
	GetItem(ctx context.Context, request GetItemRequestObject) (GetItemResponseObject, error)
	// Update an item
	// (PUT /api/v1/items/{id})
	UpdateItem(ctx context.Context, request UpdateItemRequestObject) (UpdateItemResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(ctx *gin.Context) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfile operation middleware
func (sh *strictHandler) GetProfile(ctx *gin.Context) {
	var request GetProfileRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfile(ctx, request.(GetProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetProfileResponseObject); ok {
		if err := validResponse.VisitGetProfileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx *gin.Context) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx *gin.Context) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListItems operation middleware
func (sh *strictHandler) ListItems(ctx *gin.Context, params ListItemsParams) {
	var request ListItemsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListItems(ctx, request.(ListItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListItemsResponseObject); ok {
		if err := validResponse.VisitListItemsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateItem operation middleware
func (sh *strictHandler) CreateItem(ctx *gin.Context) {
	var request CreateItemRequestObject

	var body CreateItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateItem(ctx, request.(CreateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateItemResponseObject); ok {
		if err := validResponse.VisitCreateItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteItem operation middleware
func (sh *strictHandler) DeleteItem(ctx *gin.Context, id int) {
	var request DeleteItemRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteItem(ctx, request.(DeleteItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteItemResponseObject); ok {
		if err := validResponse.VisitDeleteItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetItem operation middleware
func (sh *strictHandler) GetItem(ctx *gin.Context, id int) {
	var request GetItemRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetItem(ctx, request.(GetItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetItemResponseObject); ok {
		if err := validResponse.VisitGetItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateItem operation middleware
func (sh *strictHandler) UpdateItem(ctx *gin.Context, id int) {
	var request UpdateItemRequestObject

	request.Id = id

	var body UpdateItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateItem(ctx, request.(UpdateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateItemResponseObject); ok {
		if err := validResponse.VisitUpdateItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W4jNRR+FctwOW3S/UHL3HXZH4JWS7U/cLGKKnfmJPGux561PW3TKncggXgDkBDc",
	"ccUlEg9EgbdAx3aSmcxMktJtlcDeZcb28XfO+c6PPTmnicpyJUFaQ+NzapIRZMz93C/s6BmYXEkD+Jxr",
	"lYO2HNwoSxIw5tCqNyDx2Y5zoDE1VnM5pJOIahhoMKMlMwoDGgc+1DCgMf2gM4fSCTg6Lw3oGYjJJJpK",
	"UUevIbEo5RMNzELPQvYM3hZgbB1rCibRPLdcNQMxltnCzQRZZDR+RVli+THQiHIZfvaj+jrLrXCmydjp",
	"E5BDO6LxrW63NtNZ423BNaQo3C/rN+jyUGul222eqBRq+tCnSu6cgVaE5bngCcPXBFAScQtm+3BpYQga",
	"N0qZZXVJ++KEjQ2RhRBkoHQQogMeQyOKQ+wIlba6gElEMzCGDRtQfVpkTO5oYCnOD6Kms1dZKOB2KOd7",
	"NFnM+73VYI4b6SFzpBgoneEvlAs7lmcNQKKVZOFp6XXJpHMStfOkHgJ5emmAGDaHzSia4uOJGnLZGhqQ",
	"MS4qe/s3DfvmzJgTpdMGRRbcNxUxW9HkuQM2hBTdZ9r9x3G48mNZrqhwYW4KpjUbewWG0Ow7HDk0/Kxl",
	"2CrLxJKhQ1xv1nXIM58YW12yKnEuGLs6vd+44ZAbi3n03ZKglPX2MOtlXE6fP2rhrWTZYsK8W115e1Vu",
	"mImJ1uPZ6nTanh6r6a5BeCn91VHXZr900b7ppaoOu1yD28mzdqbUqi0blhiyEhcaA5JCczt+jgnAo7kP",
	"TIPG1gWfjtzToymrP/vyBY18i4OS/Oic5SNrczpBwVwOlGeItCxxbvK46GP1FE4teQFZLpiFWsGg+72d",
	"R5qDTMWY/PH1Lxc/ffP3z7//+cOvf331/cW33138+BvZP+jRmUMWBYbRY9DGy9vb7e52cRuVg2Q5pzG9",
	"vdvdve1ob0dO6Q7Leed4r8MKO+oIzPfOTcoTDJ3lmoJeSmNfDtCj1IcVGHtfpeOptiDdmlIr0XltPBd9",
	"ml2VhCvlZlIN3tAzzBuK+Jze6nYvtTcT4vMBjV8tR1EqA7UIC7G9bHml9Z1MJn2nSNXRTlFiCtcHDwqB",
	"PrpzSWWWYaj2gg0AvmCCp6VuzwPYuzkAPXmMEEiiIQVpORMGMdy9SSP0pMWcIYgBfQx6aglMDkWWMT2e",
	"eeqE21EFakQtGxpMoS5d9CN6upPxNBVwwjTsDLUqchrTvDgSPHEiK3GWazXgPpENoSHQHoM9CFO2gfIL",
	"B61GyuMcMtX7ptn2UqLZleZnkPrN79zg5qi5VJYMVCHTTWJ5KIGOHuXi96o/6ZeD4DFYkhRag7SkKPtx",
	"zTBA42PkJHheqUdD6ELb607oel+4LvV6Ss9CY/1fLj7OjCQYfRoP/8faozSB0xw9PLUG8QehTSxEgaDE",
	"350FoFcsQzoc7pZFnp9xjU3f4glzrdDb287Q87p6+25e+/fxzQF4iAc/woQGlo7JlIeQbmjoeXiEEQkn",
	"rgJeIfJm11GNnd8Tbqy72HJnNM0ysKCN4y6ezOjbAvSYRtMjZe5vROfGSGHACmFpvBc1XCi1C/E3WM2S",
	"uuuLegNjd5lSFlQ7jTcvDbcT5ZWXuabAjmXz63PDxWVLqjhgQy6xXyKeMFvYNiKXPXp/gMq9Sih/Hj6e",
	"7Gt2jlFLmZp/x7mmIlX/ULStZap60d3MPZxDwvePjahN28Z8T5dQL7in5b8i/GLd6JzzdOKzswAL9Uh4",
	"4N6HSGgqIDmzo3nS5SldZHFD6p6n/asm2fWI3cJIr/PNH+Dd5lt9gH+uBjaYjzB5JUZGrTdWG0u6zcqr",
	"KVjG/W3nexZf+hoKqUuOxqT34Ao9RNFA4Pn3tevj8LvvS+pfBbf15mrt+Al/e9iQM/P7AL5EAHu2XrUC",
	"lXqiIheKpTQ+x3cjYMKOzsKTu1lwDw4hQvbBXNXqARyDUHkG0gbFaEQLLcIn3bjTESphYqSMje9173Xp",
	"pD/5JwAA//8y2Eup+CYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
