// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AuthSuccessResponseCode.
const (
	AuthSuccessResponseCodeN0 AuthSuccessResponseCode = 0
)

// Valid indicates whether the value is a known member of the AuthSuccessResponseCode enum.
func (e AuthSuccessResponseCode) Valid() bool {
	switch e {
	case AuthSuccessResponseCodeN0:
		return true
	default:
		return false
	}
}

// Defines values for AuthSuccessResponseMessage.
const (
	AuthSuccessResponseMessageSuccess AuthSuccessResponseMessage = "success"
)

// Valid indicates whether the value is a known member of the AuthSuccessResponseMessage enum.
func (e AuthSuccessResponseMessage) Valid() bool {
	switch e {
	case AuthSuccessResponseMessageSuccess:
		return true
	default:
		return false
	}
}

// Defines values for CreateItemRequestStatus.
const (
	CreateItemRequestStatusActive   CreateItemRequestStatus = "active"
	CreateItemRequestStatusInactive CreateItemRequestStatus = "inactive"
)

// Valid indicates whether the value is a known member of the CreateItemRequestStatus enum.
func (e CreateItemRequestStatus) Valid() bool {
	switch e {
	case CreateItemRequestStatusActive:
		return true
	case CreateItemRequestStatusInactive:
		return true
	default:
		return false
	}
}

// Defines values for EmptySuccessResponseCode.
const (
	EmptySuccessResponseCodeN0 EmptySuccessResponseCode = 0
)

// Valid indicates whether the value is a known member of the EmptySuccessResponseCode enum.
func (e EmptySuccessResponseCode) Valid() bool {
	switch e {
	case EmptySuccessResponseCodeN0:
		return true
	default:
		return false
	}
}

// Defines values for EmptySuccessResponseMessage.
const (
	EmptySuccessResponseMessageSuccess EmptySuccessResponseMessage = "success"
)

// Valid indicates whether the value is a known member of the EmptySuccessResponseMessage enum.
func (e EmptySuccessResponseMessage) Valid() bool {
	switch e {
	case EmptySuccessResponseMessageSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ItemSuccessResponseCode.
const (
	ItemSuccessResponseCodeN0 ItemSuccessResponseCode = 0
)

// Valid indicates whether the value is a known member of the ItemSuccessResponseCode enum.
func (e ItemSuccessResponseCode) Valid() bool {
	switch e {
	case ItemSuccessResponseCodeN0:
		return true
	default:
		return false
	}
}

// Defines values for ItemSuccessResponseMessage.
const (
	ItemSuccessResponseMessageSuccess ItemSuccessResponseMessage = "success"
)

// Valid indicates whether the value is a known member of the ItemSuccessResponseMessage enum.
func (e ItemSuccessResponseMessage) Valid() bool {
	switch e {
	case ItemSuccessResponseMessageSuccess:
		return true
	default:
		return false
	}
}

// Defines values for PagedItemsSuccessResponseCode.
const (
	PagedItemsSuccessResponseCodeN0 PagedItemsSuccessResponseCode = 0
)

// Valid indicates whether the value is a known member of the PagedItemsSuccessResponseCode enum.
func (e PagedItemsSuccessResponseCode) Valid() bool {
	switch e {
	case PagedItemsSuccessResponseCodeN0:
		return true
	default:
		return false
	}
}

// Defines values for PagedItemsSuccessResponseMessage.
const (
	PagedItemsSuccessResponseMessageSuccess PagedItemsSuccessResponseMessage = "success"
)

// Valid indicates whether the value is a known member of the PagedItemsSuccessResponseMessage enum.
func (e PagedItemsSuccessResponseMessage) Valid() bool {
	switch e {
	case PagedItemsSuccessResponseMessageSuccess:
		return true
	default:
		return false
	}
}

// Defines values for UpdateItemRequestStatus.
const (
	UpdateItemRequestStatusActive   UpdateItemRequestStatus = "active"
	UpdateItemRequestStatusInactive UpdateItemRequestStatus = "inactive"
)

// Valid indicates whether the value is a known member of the UpdateItemRequestStatus enum.
func (e UpdateItemRequestStatus) Valid() bool {
	switch e {
	case UpdateItemRequestStatusActive:
		return true
	case UpdateItemRequestStatusInactive:
		return true
	default:
		return false
	}
}

// Defines values for UserSuccessResponseCode.
const (
	N0 UserSuccessResponseCode = 0
)

// Valid indicates whether the value is a known member of the UserSuccessResponseCode enum.
func (e UserSuccessResponseCode) Valid() bool {
	switch e {
	case N0:
		return true
	default:
		return false
	}
}

// Defines values for UserSuccessResponseMessage.
const (
	Success UserSuccessResponseMessage = "success"
)

// Valid indicates whether the value is a known member of the UserSuccessResponseMessage enum.
func (e UserSuccessResponseMessage) Valid() bool {
	switch e {
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for ListItemsParamsStatus.
const (
	Active   ListItemsParamsStatus = "active"
	Inactive ListItemsParamsStatus = "inactive"
)

// Valid indicates whether the value is a known member of the ListItemsParamsStatus enum.
func (e ListItemsParamsStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token"`
	User         UserResponse `json:"user"`
}

// AuthSuccessResponse defines model for AuthSuccessResponse.
type AuthSuccessResponse struct {
	Code    AuthSuccessResponseCode    `json:"code"`
	Data    AuthResponse               `json:"data"`
	Message AuthSuccessResponseMessage `json:"message"`
}

// AuthSuccessResponseCode defines model for AuthSuccessResponse.Code.
type AuthSuccessResponseCode int

// AuthSuccessResponseMessage defines model for AuthSuccessResponse.Message.
type AuthSuccessResponseMessage string

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	Description *string                  `json:"description,omitempty"`
	Status      *CreateItemRequestStatus `json:"status,omitempty"`
	Title       string                   `json:"title"`
}

// CreateItemRequestStatus defines model for CreateItemRequest.Status.
type CreateItemRequestStatus string

// EmptySuccessResponse defines model for EmptySuccessResponse.
type EmptySuccessResponse struct {
	Code EmptySuccessResponseCode `json:"code"`

	// Data Null for successful operations without a payload
	Data    interface{}                 `json:"data"`
	Message EmptySuccessResponseMessage `json:"message"`
}

// EmptySuccessResponseCode defines model for EmptySuccessResponse.Code.
type EmptySuccessResponseCode int

// EmptySuccessResponseMessage defines model for EmptySuccessResponse.Message.
type EmptySuccessResponseMessage string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Non-zero application error code
	Code int `json:"code"`

	// Data Always null for error responses
	Data interface{} `json:"data"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// ItemResponse defines model for ItemResponse.
type ItemResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Id          int       `json:"id"`
	Status      string    `json:"status"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
	UserId      int       `json:"user_id"`
}

// ItemSuccessResponse defines model for ItemSuccessResponse.
type ItemSuccessResponse struct {
	Code    ItemSuccessResponseCode    `json:"code"`
	Data    ItemResponse               `json:"data"`
	Message ItemSuccessResponseMessage `json:"message"`
}

// ItemSuccessResponseCode defines model for ItemSuccessResponse.Code.
type ItemSuccessResponseCode int

// ItemSuccessResponseMessage defines model for ItemSuccessResponse.Message.
type ItemSuccessResponseMessage string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PagedItemsResponse defines model for PagedItemsResponse.
type PagedItemsResponse struct {
	Items      []ItemResponse `json:"items"`
	Page       int            `json:"page"`
	PageSize   int            `json:"page_size"`
	Total      int            `json:"total"`
	TotalPages int            `json:"total_pages"`
}

// PagedItemsSuccessResponse defines model for PagedItemsSuccessResponse.
type PagedItemsSuccessResponse struct {
	Code    PagedItemsSuccessResponseCode    `json:"code"`
	Data    PagedItemsResponse               `json:"data"`
	Message PagedItemsSuccessResponseMessage `json:"message"`
}

// PagedItemsSuccessResponseCode defines model for PagedItemsSuccessResponse.Code.
type PagedItemsSuccessResponseCode int

// PagedItemsSuccessResponseMessage defines model for PagedItemsSuccessResponse.Message.
type PagedItemsSuccessResponseMessage string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// UpdateItemRequest defines model for UpdateItemRequest.
type UpdateItemRequest struct {
	Description *string                  `json:"description,omitempty"`
	Status      *UpdateItemRequestStatus `json:"status,omitempty"`
	Title       *string                  `json:"title,omitempty"`
}

// UpdateItemRequestStatus defines model for UpdateItemRequest.Status.
type UpdateItemRequestStatus string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email    string `json:"email"`
	Id       int    `json:"id"`
	Role     string `json:"role"`
	Username string `json:"username"`
}

// UserSuccessResponse defines model for UserSuccessResponse.
type UserSuccessResponse struct {
	Code    UserSuccessResponseCode    `json:"code"`
	Data    UserResponse               `json:"data"`
	Message UserSuccessResponseMessage `json:"message"`
}

// UserSuccessResponseCode defines model for UserSuccessResponse.Code.
type UserSuccessResponseCode int

// UserSuccessResponseMessage defines model for UserSuccessResponse.Message.
type UserSuccessResponseMessage string

// XRequestID defines model for XRequestID.
type XRequestID = string

// LoginUserParams defines parameters for LoginUser.
type LoginUserParams struct {
	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GetProfileParams defines parameters for GetProfile.
type GetProfileParams struct {
	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// RefreshTokenParams defines parameters for RefreshToken.
type RefreshTokenParams struct {
	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// RegisterUserParams defines parameters for RegisterUser.
type RegisterUserParams struct {
	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	Page     *int                   `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int                   `form:"page_size,omitempty" json:"page_size,omitempty"`
	Keyword  *string                `form:"keyword,omitempty" json:"keyword,omitempty"`
	Status   *ListItemsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// ListItemsParamsStatus defines parameters for ListItems.
type ListItemsParamsStatus string

// CreateItemParams defines parameters for CreateItem.
type CreateItemParams struct {
	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// DeleteItemParams defines parameters for DeleteItem.
type DeleteItemParams struct {
	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GetItemParams defines parameters for GetItem.
type GetItemParams struct {
	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// UpdateItemParams defines parameters for UpdateItem.
type UpdateItemParams struct {
	// XRequestID Optional caller-supplied request ID used for request/response log correlation.
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = UpdateItemRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with credentials
	// (POST /api/v1/auth/login)
	LoginUser(c *gin.Context, params LoginUserParams)
	// Get current user profile
	// (GET /api/v1/auth/profile)
	GetProfile(c *gin.Context, params GetProfileParams)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(c *gin.Context, params RefreshTokenParams)
	// Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(c *gin.Context, params RegisterUserParams)
	// List items with pagination
	// (GET /api/v1/items)
	ListItems(c *gin.Context, params ListItemsParams)
	// Create a new item
	// (POST /api/v1/items)
	CreateItem(c *gin.Context, params CreateItemParams)
	// Soft delete an item
	// (DELETE /api/v1/items/{id})
	DeleteItem(c *gin.Context, id int, params DeleteItemParams)
	// Get item by ID
	// (GET /api/v1/items/{id})
	GetItem(c *gin.Context, id int, params GetItemParams)
	// Update an item
	// (PUT /api/v1/items/{id})
	UpdateItem(c *gin.Context, id int, params UpdateItemParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginUserParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginUser(c, params)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProfileParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfile(c, params)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshTokenParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c, params)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterUserParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterUser(c, params)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "keyword" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "keyword", c.Request.URL.Query(), &params.Keyword, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter keyword: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListItems(c, params)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateItemParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateItem(c, params)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteItemParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteItem(c, id, params)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetItemParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItem(c, id, params)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateItemParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateItem(c, id, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.LoginUser)
	router.GET(options.BaseURL+"/api/v1/auth/profile", wrapper.GetProfile)
	router.POST(options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshToken)
	router.POST(options.BaseURL+"/api/v1/auth/register", wrapper.RegisterUser)
	router.GET(options.BaseURL+"/api/v1/items", wrapper.ListItems)
	router.POST(options.BaseURL+"/api/v1/items", wrapper.CreateItem)
	router.DELETE(options.BaseURL+"/api/v1/items/:id", wrapper.DeleteItem)
	router.GET(options.BaseURL+"/api/v1/items/:id", wrapper.GetItem)
	router.PUT(options.BaseURL+"/api/v1/items/:id", wrapper.UpdateItem)
}

type LoginUserRequestObject struct {
	Params LoginUserParams
	Body   *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200ResponseHeaders struct {
	XRequestID string
}

type LoginUser200JSONResponse struct {
	Body    AuthSuccessResponse
	Headers LoginUser200ResponseHeaders
}

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type LoginUser400ResponseHeaders struct {
	XRequestID string
}

type LoginUser400JSONResponse struct {
	Body    ErrorResponse
	Headers LoginUser400ResponseHeaders
}

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type LoginUser401ResponseHeaders struct {
	XRequestID string
}

type LoginUser401JSONResponse struct {
	Body    ErrorResponse
	Headers LoginUser401ResponseHeaders
}

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type LoginUser500ResponseHeaders struct {
	XRequestID string
}

type LoginUser500JSONResponse struct {
	Body    ErrorResponse
	Headers LoginUser500ResponseHeaders
}

func (response LoginUser500JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProfileRequestObject struct {
	Params GetProfileParams
}

type GetProfileResponseObject interface {
	VisitGetProfileResponse(w http.ResponseWriter) error
}

type GetProfile200ResponseHeaders struct {
	XRequestID string
}

type GetProfile200JSONResponse struct {
	Body    UserSuccessResponse
	Headers GetProfile200ResponseHeaders
}

func (response GetProfile200JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProfile400ResponseHeaders struct {
	XRequestID string
}

type GetProfile400JSONResponse struct {
	Body    ErrorResponse
	Headers GetProfile400ResponseHeaders
}

func (response GetProfile400JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProfile401ResponseHeaders struct {
	XRequestID string
}

type GetProfile401JSONResponse struct {
	Body    ErrorResponse
	Headers GetProfile401ResponseHeaders
}

func (response GetProfile401JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProfile404ResponseHeaders struct {
	XRequestID string
}

type GetProfile404JSONResponse struct {
	Body    ErrorResponse
	Headers GetProfile404ResponseHeaders
}

func (response GetProfile404JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProfile500ResponseHeaders struct {
	XRequestID string
}

type GetProfile500JSONResponse struct {
	Body    ErrorResponse
	Headers GetProfile500ResponseHeaders
}

func (response GetProfile500JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

type RefreshTokenRequestObject struct {
	Params RefreshTokenParams
	Body   *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200ResponseHeaders struct {
	XRequestID string
}

type RefreshToken200JSONResponse struct {
	Body    AuthSuccessResponse
	Headers RefreshToken200ResponseHeaders
}

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type RefreshToken400ResponseHeaders struct {
	XRequestID string
}

type RefreshToken400JSONResponse struct {
	Body    ErrorResponse
	Headers RefreshToken400ResponseHeaders
}

func (response RefreshToken400JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type RefreshToken401ResponseHeaders struct {
	XRequestID string
}

type RefreshToken401JSONResponse struct {
	Body    ErrorResponse
	Headers RefreshToken401ResponseHeaders
}

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type RefreshToken500ResponseHeaders struct {
	XRequestID string
}

type RefreshToken500JSONResponse struct {
	Body    ErrorResponse
	Headers RefreshToken500ResponseHeaders
}

func (response RefreshToken500JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterUserRequestObject struct {
	Params RegisterUserParams
	Body   *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201ResponseHeaders struct {
	XRequestID string
}

type RegisterUser201JSONResponse struct {
	Body    AuthSuccessResponse
	Headers RegisterUser201ResponseHeaders
}

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterUser400ResponseHeaders struct {
	XRequestID string
}

type RegisterUser400JSONResponse struct {
	Body    ErrorResponse
	Headers RegisterUser400ResponseHeaders
}

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterUser409ResponseHeaders struct {
	XRequestID string
}

type RegisterUser409JSONResponse struct {
	Body    ErrorResponse
	Headers RegisterUser409ResponseHeaders
}

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterUser500ResponseHeaders struct {
	XRequestID string
}

type RegisterUser500JSONResponse struct {
	Body    ErrorResponse
	Headers RegisterUser500ResponseHeaders
}

func (response RegisterUser500JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListItemsRequestObject struct {
	Params ListItemsParams
}

type ListItemsResponseObject interface {
	VisitListItemsResponse(w http.ResponseWriter) error
}

type ListItems200ResponseHeaders struct {
	XRequestID string
}

type ListItems200JSONResponse struct {
	Body    PagedItemsSuccessResponse
	Headers ListItems200ResponseHeaders
}

func (response ListItems200JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListItems400ResponseHeaders struct {
	XRequestID string
}

type ListItems400JSONResponse struct {
	Body    ErrorResponse
	Headers ListItems400ResponseHeaders
}

func (response ListItems400JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListItems500ResponseHeaders struct {
	XRequestID string
}

type ListItems500JSONResponse struct {
	Body    ErrorResponse
	Headers ListItems500ResponseHeaders
}

func (response ListItems500JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateItemRequestObject struct {
	Params CreateItemParams
	Body   *CreateItemJSONRequestBody
}

type CreateItemResponseObject interface {
	VisitCreateItemResponse(w http.ResponseWriter) error
}

type CreateItem201ResponseHeaders struct {
	XRequestID string
}

type CreateItem201JSONResponse struct {
	Body    ItemSuccessResponse
	Headers CreateItem201ResponseHeaders
}

func (response CreateItem201JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateItem400ResponseHeaders struct {
	XRequestID string
}

type CreateItem400JSONResponse struct {
	Body    ErrorResponse
	Headers CreateItem400ResponseHeaders
}

func (response CreateItem400JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateItem500ResponseHeaders struct {
	XRequestID string
}

type CreateItem500JSONResponse struct {
	Body    ErrorResponse
	Headers CreateItem500ResponseHeaders
}

func (response CreateItem500JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteItemRequestObject struct {
	Id     int `json:"id"`
	Params DeleteItemParams
}

type DeleteItemResponseObject interface {
	VisitDeleteItemResponse(w http.ResponseWriter) error
}

type DeleteItem200ResponseHeaders struct {
	XRequestID string
}

type DeleteItem200JSONResponse struct {
	Body    EmptySuccessResponse
	Headers DeleteItem200ResponseHeaders
}

func (response DeleteItem200JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteItem400ResponseHeaders struct {
	XRequestID string
}

type DeleteItem400JSONResponse struct {
	Body    ErrorResponse
	Headers DeleteItem400ResponseHeaders
}

func (response DeleteItem400JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteItem404ResponseHeaders struct {
	XRequestID string
}

type DeleteItem404JSONResponse struct {
	Body    ErrorResponse
	Headers DeleteItem404ResponseHeaders
}

func (response DeleteItem404JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteItem500ResponseHeaders struct {
	XRequestID string
}

type DeleteItem500JSONResponse struct {
	Body    ErrorResponse
	Headers DeleteItem500ResponseHeaders
}

func (response DeleteItem500JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetItemRequestObject struct {
	Id     int `json:"id"`
	Params GetItemParams
}

type GetItemResponseObject interface {
	VisitGetItemResponse(w http.ResponseWriter) error
}

type GetItem200ResponseHeaders struct {
	XRequestID string
}

type GetItem200JSONResponse struct {
	Body    ItemSuccessResponse
	Headers GetItem200ResponseHeaders
}

func (response GetItem200JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetItem400ResponseHeaders struct {
	XRequestID string
}

type GetItem400JSONResponse struct {
	Body    ErrorResponse
	Headers GetItem400ResponseHeaders
}

func (response GetItem400JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetItem404ResponseHeaders struct {
	XRequestID string
}

type GetItem404JSONResponse struct {
	Body    ErrorResponse
	Headers GetItem404ResponseHeaders
}

func (response GetItem404JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetItem500ResponseHeaders struct {
	XRequestID string
}

type GetItem500JSONResponse struct {
	Body    ErrorResponse
	Headers GetItem500ResponseHeaders
}

func (response GetItem500JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateItemRequestObject struct {
	Id     int `json:"id"`
	Params UpdateItemParams
	Body   *UpdateItemJSONRequestBody
}

type UpdateItemResponseObject interface {
	VisitUpdateItemResponse(w http.ResponseWriter) error
}

type UpdateItem200ResponseHeaders struct {
	XRequestID string
}

type UpdateItem200JSONResponse struct {
	Body    ItemSuccessResponse
	Headers UpdateItem200ResponseHeaders
}

func (response UpdateItem200JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateItem400ResponseHeaders struct {
	XRequestID string
}

type UpdateItem400JSONResponse struct {
	Body    ErrorResponse
	Headers UpdateItem400ResponseHeaders
}

func (response UpdateItem400JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateItem404ResponseHeaders struct {
	XRequestID string
}

type UpdateItem404JSONResponse struct {
	Body    ErrorResponse
	Headers UpdateItem404ResponseHeaders
}

func (response UpdateItem404JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateItem500ResponseHeaders struct {
	XRequestID string
}

type UpdateItem500JSONResponse struct {
	Body    ErrorResponse
	Headers UpdateItem500ResponseHeaders
}

func (response UpdateItem500JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login with credentials
	// (POST /api/v1/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Get current user profile
	// (GET /api/v1/auth/profile)
	GetProfile(ctx context.Context, request GetProfileRequestObject) (GetProfileResponseObject, error)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// List items with pagination
	// (GET /api/v1/items)
	ListItems(ctx context.Context, request ListItemsRequestObject) (ListItemsResponseObject, error)
	// Create a new item
	// (POST /api/v1/items)
	CreateItem(ctx context.Context, request CreateItemRequestObject) (CreateItemResponseObject, error)
	// Soft delete an item
	// (DELETE /api/v1/items/{id})
	DeleteItem(ctx context.Context, request DeleteItemRequestObject) (DeleteItemResponseObject, error)
	// Get item by ID
	// (GET /api/v1/items/{id})
	GetItem(ctx context.Context, request GetItemRequestObject) (GetItemResponseObject, error)
	// Update an item
	// (PUT /api/v1/items/{id})
	UpdateItem(ctx context.Context, request UpdateItemRequestObject) (UpdateItemResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(ctx *gin.Context, params LoginUserParams) {
	var request LoginUserRequestObject

	request.Params = params

	var body LoginUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfile operation middleware
func (sh *strictHandler) GetProfile(ctx *gin.Context, params GetProfileParams) {
	var request GetProfileRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfile(ctx, request.(GetProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetProfileResponseObject); ok {
		if err := validResponse.VisitGetProfileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx *gin.Context, params RefreshTokenParams) {
	var request RefreshTokenRequestObject

	request.Params = params

	var body RefreshTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx *gin.Context, params RegisterUserParams) {
	var request RegisterUserRequestObject

	request.Params = params

	var body RegisterUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListItems operation middleware
func (sh *strictHandler) ListItems(ctx *gin.Context, params ListItemsParams) {
	var request ListItemsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListItems(ctx, request.(ListItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListItemsResponseObject); ok {
		if err := validResponse.VisitListItemsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateItem operation middleware
func (sh *strictHandler) CreateItem(ctx *gin.Context, params CreateItemParams) {
	var request CreateItemRequestObject

	request.Params = params

	var body CreateItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateItem(ctx, request.(CreateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateItemResponseObject); ok {
		if err := validResponse.VisitCreateItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteItem operation middleware
func (sh *strictHandler) DeleteItem(ctx *gin.Context, id int, params DeleteItemParams) {
	var request DeleteItemRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteItem(ctx, request.(DeleteItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteItemResponseObject); ok {
		if err := validResponse.VisitDeleteItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetItem operation middleware
func (sh *strictHandler) GetItem(ctx *gin.Context, id int, params GetItemParams) {
	var request GetItemRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetItem(ctx, request.(GetItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetItemResponseObject); ok {
		if err := validResponse.VisitGetItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateItem operation middleware
func (sh *strictHandler) UpdateItem(ctx *gin.Context, id int, params UpdateItemParams) {
	var request UpdateItemRequestObject

	request.Id = id
	request.Params = params

	var body UpdateItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateItem(ctx, request.(UpdateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateItemResponseObject); ok {
		if err := validResponse.VisitUpdateItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW28bNxb+KwR3H0eWnMsiO2/O2slqEWSNXNoAhmHQwyOJCYeckBzbsqG3FmjRf9AC",
	"RfvWpz4W6A9q2v6LgpfRzFgzkmwrqpPoTXM7PLfv4zkkdYETmWZSgDAaxxd4BISCcj9fPYO3OWjT37VX",
	"FHSiWGaYFDjGe4MBJIadAFL+JdTfRURrmTBigKJTZkbIjJhGCnQmhYYtHGGdjCAlVpoZZ4BjrI1iYogn",
	"k0mEM6JICmaJwf/vfhCOEsI5qI7Os4wzoFVdcg0UDaQq7nULPRCXQ5RIpYATK8bqxaxUbzmOsCCp1e1V",
	"J6jQ6e8u0t0/dIrv5Gb0LIxlrzMlM1CGgXtKkgS0PjLyDYgGWRFWMFCgR3PeyDUo++CfCgY4xv/olgHs",
	"Bj26LzWoqRITJ/ZtzhRQHB/Udbg8YpB/GBUDy+PXkBg7sLXsee4+bjcwkdTdBZGnOD7olYKYMDAEZSVR",
	"YsgiE2p+nEQ4Ba3JsCoba69MRdlpTOoWO6XCsKWkJhv/o4AY6BtIQ/BnLazlYkN8tCEm11U9iUOKy7Pw",
	"c1bjCBtmuDMvJWdPQAzNCMd3er1FtvnPmmzZSzMzXm3A6jh8mnPuMBYCMcg5sqIdrrTjAJkbRFBGxlwS",
	"arGVc06OrZ1G5bC2sO4pJdViH1wyT4rOOSiJiKWXxFmFwEpCYeRlHbXDT8lYI1H4ywspGEkv8Etd1n/z",
	"lIiOAkLt+0FU8fbqPOYh0OowBxN6RBw+BlKl9peVCx3D0gZFooW4YbRyu+LSEk/tkJklyYxeWUFLfEfN",
	"WlxyI7Op7Aev2zXVtpQWVZ1VU6zN7evj2FqQ1wbGJ3LIRCu9QkoYrwXN32kIWEa0PpWKNk3KdeUKEdMv",
	"mvTaJ0Og1iVzXM/s49qPq/g3DEmUImNvwBCak94+OdLsvOWxkYbwOY+O7Pd6mUx2ZhQCg0bV4esC57tt",
	"fYnbEKq1pe8zXy+1JvCiCu7SwPXXmwccMm1sQbdayFTqjG1bZ6RMFNf/aqFHXxrXPr1f//LuIkdPxUTL",
	"ofKlI8zbXpHNql2twNsjtvQsqGTbTFcJy3zPu8mowf1O9GGLDevDdL1nWQ+abXJAkitmxs+tGt6kh0AU",
	"KNuA2Ktjd/WogNb/Pn9RdINWkn9aQm1kTOZ7QiYG0jtIGJK4tA2d5WP5FM4MegFpxomBmeII7/Q7jxQD",
	"QfkY/fblT+9++OrPH3/9/buf//ji23dff/Pu+1/Qzn5/WoLMCAxPT0BpL297q7fVs8PIDATJGI7x3a3e",
	"1l2HPTNyRndJxron212Sm1GX2ynaxVp6wE3L+j7FsZ/BbbxwvW0/aI5w+Uq30tZPDn3MQJuHko4LV4Fw",
	"A1Zq7u5r7YFdtuDz8qhWXkzqmRGK67Lyji/wnV5vZWM3tchOhXp8nYqVrglHtXWX6sJDy4Dh9Zo/7Tj3",
	"VmhMvWlqMOMzwhmttEWrNGN7fWb0xYk1BCUKKAjDCNers+T+OgPSF8ayO0ca1Amo1UbFcmWepkSNpxns",
	"VvnqbjNkaInALRZZwj3rpIxSDqdEQWeoZJ7hGGf5MWeJo98a7WRKDpif54bQwDuPweyHV25MPO+JAZrm",
	"zIZI2ddQNrXlQ0R/AZvA4R8o+F8Km3lSsXOgqzTh3hpNsLkkpEEDmQu6oa5m6gplnuOKaoF3cGj5oGS2",
	"x2BQkisFwqC8jtKluM2mk6XDhBigsxQX2r322iq0ly/CavytK68utb+3s8By3kPB16sF9qa+uu5EIRWC",
	"s8zmSREZVOw5bRhrXrEVIIf8xt3UaTcqtVRYVJpHRP6N29rnXV4WW4qJttfNRF5L79ZNxzfPjH+vz4y9",
	"lDCOCFdA6BgVUIBN7bSYibyrEEECTl19dAMimu6hNDZ7T5g2/bA9cX3yiS786Y63Oahxebgj7HOUAaAw",
	"IDk3ON6OGvZM2oUUuyRNknrLi3oDY7cCPu+cScun0x3H8surLHO/1264fW+oIY33yZAJd3qo2JXatMWf",
	"fDtmWcDng19tynyS+M32gng8TSzZkUUt9U559Oc2VjuzB5PWXO80nUxoShwDKQonHjZFzgbCU2CFkoF5",
	"fF0LuZdLh+4FoxM/5XIwMAvpXXf/xpAuJt6MmFE577rt1Dr+GmbvcuZ/n/Ns41G/NnR6b9HN/Po3rtm6",
	"QGzWbFfEMM/lwIS0RkTciGOi1p2nT4BGrjLHUzCE8U2VvmGRj2nnx1IHOh4j95eP67YXeQOBlMfYbguH",
	"rL5HmT2qt+bdoavwVziIvelRNgT2sRCYx99NK6BKl5Vn7m878YW9NwLCzeg8XLmlc3fhNLSGezKr+2YX",
	"ToDLLAVhgntwhHPFw0nJuNvlMiF8JLWJH/Qe9PDkcPJXAAAA//9KtvWSkzgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
