/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["livenessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: operations["readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with credentials */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List items with pagination */
        get: operations["listItems"];
        put?: never;
        /** Create a new item */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get item by ID */
        get: operations["getItem"];
        /** Update an item */
        put: operations["updateItem"];
        post?: never;
        /** Soft delete an item */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Response: {
            code: number;
            data: unknown;
            message: string;
        };
        ErrorResponse: {
            /** @description Non-zero application error code */
            code: number;
            /** @description Human-readable error message */
            message: string;
            /** @description Request ID for backend log correlation */
            request_id: string;
            /** @description Optional structured diagnostics for error handling */
            details?: ({
                [key: string]: unknown;
            } | unknown[] | string) | null;
        };
        RegisterRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        AuthResponse: {
            access_token: string;
            refresh_token: string;
            user: components["schemas"]["UserResponse"];
        };
        UserResponse: {
            id: number;
            username: string;
            email: string;
            role: string;
        };
        CreateItemRequest: {
            title: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        UpdateItemRequest: {
            title?: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        ItemResponse: {
            id: number;
            title: string;
            description: string;
            status: string;
            user_id: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PagedItemsResponse: {
            items: components["schemas"]["ItemResponse"][];
            total: number;
            page: number;
            page_size: number;
            total_pages: number;
        };
        UploadResponse: {
            url: string;
            filename: string;
            size: number;
        };
        AuthSuccessResponse: {
            /** @enum {integer} */
            code: 0;
            data: components["schemas"]["AuthResponse"];
            /** @enum {string} */
            message: "success";
        };
        UserSuccessResponse: {
            /** @enum {integer} */
            code: 0;
            data: components["schemas"]["UserResponse"];
            /** @enum {string} */
            message: "success";
        };
        ItemSuccessResponse: {
            /** @enum {integer} */
            code: 0;
            data: components["schemas"]["ItemResponse"];
            /** @enum {string} */
            message: "success";
        };
        PagedItemsSuccessResponse: {
            /** @enum {integer} */
            code: 0;
            data: components["schemas"]["PagedItemsResponse"];
            /** @enum {string} */
            message: "success";
        };
        UploadSuccessResponse: {
            /** @enum {integer} */
            code: 0;
            data: components["schemas"]["UploadResponse"];
            /** @enum {string} */
            message: "success";
        };
        EmptySuccessResponse: {
            /** @enum {integer} */
            code: 0;
            /** @description Null for successful operations without a payload */
            data: unknown;
            /** @enum {string} */
            message: "success";
        };
    };
    responses: never;
    parameters: {
        /** @description Optional caller-supplied request ID used for request/response log correlation. */
        XRequestID: string;
    };
    requestBodies: never;
    headers: {
        /** @description Effective request ID associated with this response. */
        XRequestID: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    livenessCheck: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readinessCheck: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service is not ready */
            503: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration successful */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSuccessResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listItems: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                keyword?: string;
                status?: "active" | "inactive";
            };
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated items */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedItemsSuccessResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Item created */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item details */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSuccessResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description Item updated */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item deleted */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptySuccessResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller-supplied request ID used for request/response log correlation. */
                "X-Request-ID"?: components["parameters"]["XRequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description File uploaded */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSuccessResponse"];
                };
            };
            /** @description File type not allowed */
            400: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
