// Code generated by Wire. DO NOT EDIT.

package main

import (
	"github.com/xxbbzy/gonext-template/backend/internal/config"
	"github.com/xxbbzy/gonext-template/backend/internal/handler"
	"github.com/xxbbzy/gonext-template/backend/internal/repository"
)

func InitializeApplication() (*Application, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, err
	}

	logger, err := config.NewLogger(cfg)
	if err != nil {
		return nil, err
	}

	db, err := config.NewDatabase(cfg, logger)
	if err != nil {
		return nil, err
	}

	jwtManager, err := newJWTManager(cfg)
	if err != nil {
		return nil, err
	}

	userRepository := repository.NewUserRepository(db)
	itemRepository := repository.NewItemRepository(db)
	authService := newAuthService(userRepository, jwtManager)
	itemService := newItemService(itemRepository)
	fileStorageRepository, err := newUploadStorageRepository(cfg)
	if err != nil {
		return nil, err
	}
	uploadService := newUploadService(fileStorageRepository, logger)
	authHandler := handler.NewAuthHandler(authService)
	itemHandler := handler.NewItemHandler(itemService)
	uploadHandler := handler.NewUploadHandler(uploadService, cfg)
	publicRateLimiter := newPublicRateLimiter(cfg)
	userRateLimiter := newUserRateLimiter(cfg)

	return newApplication(
		cfg,
		logger,
		db,
		jwtManager,
		authService,
		itemService,
		uploadService,
		authHandler,
		itemHandler,
		uploadHandler,
		publicRateLimiter,
		userRateLimiter,
	), nil
}
